obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.138, 0.142], [0.138, -0.142], [-0.138, -0.142], [-0.138, 0.142]] 
inflation_radius: 0.5
max_obstacle_height: 0.5
min_obstacle_height: 0.02
observation_sources: scan
# scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
scan: {data_type: LaserScan, sensor_frame: /camera_depth_frame, topic: /scan, marking: true, clearing: true}
